### ISSUE TITLE
Read commands from file

### ISSUE THREAD

**Issue by Thiana** [maruohon/worldutils#1]
Since there appears to be no way to cut and paste multiple commands into MC at once. Could you add a way for us to create a file containing worldutils commands in an external editor and then run something like `/worldutils exec <filename>` in game to apply them? Thanks.

**Comment by maruohon** [comment]
This will be in the next release. And it is in no way tied to worldutils commands, but it will simply execute any Minecraft commands from the files placed inside `config/worldutils/batch_commands/`.

**Comment by Thiana** [comment]
Thank you :)
