### ISSUE TITLE
Crash after some time after starting uuid removing command

### ISSUE THREAD

**Issue by TheRealDadbeard** [maruohon/worldutils#6]
Locally
https://hastebin.com/ipetakakan.rb

On the Server
https://hastebin.com/vacisasuzo.md

**Comment by maruohon** [comment]
It looks like at least two of your region files are corrupted somehow. I'll need to add new protection against those crashes.

Could you upload the region files `r.2.29.mca` and `r.2.30.mca` (that are indicated in the server log) somewhere? I'd like to take a look if I can figure out anything about how they are broken.

**Comment by TheRealDadbeard** [comment]
Yes of course here. Is it wise to maybe delete this files after checking out whats in there? Can I somewhow look it up? 

https://www.dropbox.com/sh/64eql8t074qva3u/AACA1TG2Wn5pXCTXm_A6b0Yra?dl=0

**Comment by maruohon** [comment]
Sorry I didn't understand what you mean? What do you mean by delete the files, do you mean in your world? And look what up?

Also, I worked on World Utils a bit today and added some more exception catching to hopefully fix the crash you had. Here is a dev build if you want to try it out: https://masa.dy.fi/tmp/minecraft/mods/worldutils/worldutils-1.12.2-0.5.0-dev.20180821.184927.jar

I'd recommend running it again for a clean copy of the world, and not the one where you already ran it and it crashed... mainly just in case the crash messed up some files.

**Comment by TheRealDadbeard** [comment]
Deleting the region files that are corrupted, thats what I meant.
